### ISSUE TITLE
使用作者提供的两个权重和测试脚本生成的结果并不能得到论文中的结果

### ISSUE THREAD

**Issue by lartpang** [liuzywen/TriTransNet#4]
- 链接：https://pan.baidu.com/s/1HMdu_2w1VcMlizjA3HOjLw 提取码：8f7t

下面是我测试的结果

### TriTransNet.pth

Dataset: DUTRGBD
| methods   |   adpe |   adpf |   avge |   avgf |   mae |   maxe |   maxf |    sm |   wfm |
|-----------|--------|--------|--------|--------|-------|--------|--------|-------|-------|
| Ours      |  0.925 |  0.881 |  0.915 |  0.874 | 0.052 |  0.922 |  0.878 | 0.876 | 0.847 |

Dataset: LFSD

| methods   |   adpe |   adpf |   avge |   avgf |   mae |   maxe |   maxf |    sm |   wfm |
|-----------|--------|--------|--------|--------|-------|--------|--------|-------|-------|
| Ours      |  0.839 |  0.787 |  0.826 |  0.776 | 0.104 |  0.847 |  0.783 | 0.788 | 0.739 |

Dataset: RGBD135

| methods   |   adpe |   adpf |   avge |   avgf |   mae |   maxe |   maxf |    sm |   wfm |
|-----------|--------|--------|--------|--------|-------|--------|--------|-------|-------|
| Ours      |  0.928 |   0.87 |  0.914 |  0.863 | 0.031 |  0.933 |  0.867 | 0.884 | 0.834 |

Dataset: SIP

| methods   |   adpe |   adpf |   avge |   avgf |   mae |   maxe |   maxf |    sm |   wfm |
|-----------|--------|--------|--------|--------|-------|--------|--------|-------|-------|
| Ours      |  0.873 |  0.815 |  0.864 |  0.809 | 0.078 |  0.878 |  0.814 | 0.814 | 0.758 |

Dataset: SSD

| methods   |   adpe |   adpf |   avge |   avgf |   mae |   maxe |   maxf |    sm |   wfm |
|-----------|--------|--------|--------|--------|-------|--------|--------|-------|-------|
| Ours      |  0.897 |  0.798 |   0.89 |  0.795 | 0.064 |  0.895 |  0.802 | 0.829 | 0.762 |

Dataset: STEREO1000

| methods   |   adpe |   adpf |   avge |   avgf |   mae |   maxe |   maxf |   sm |   wfm |
|-----------|--------|--------|--------|--------|-------|--------|--------|------|-------|
| Ours      |  0.939 |  0.881 |  0.934 |  0.878 | 0.041 |  0.938 |  0.887 | 0.89 | 0.857 |

### TriTransNet-DUT.pth

Dataset: DUTRGBD

| methods   |   adpe |   adpf |   avge |   avgf |   mae |   maxe |   maxf |    sm |   wfm |
|-----------|--------|--------|--------|--------|-------|--------|--------|-------|-------|
| OursDUT   |  0.947 |  0.905 |  0.943 |  0.902 | 0.037 |  0.947 |   0.91 | 0.906 | 0.886 |

Dataset: LFSD

| methods   |   adpe |   adpf |   avge |   avgf |   mae |   maxe |   maxf |    sm |   wfm |
|-----------|--------|--------|--------|--------|-------|--------|--------|-------|-------|
| OursDUT   |  0.874 |  0.812 |  0.868 |  0.808 | 0.092 |  0.877 |  0.818 | 0.822 | 0.782 |

Dataset: RGBD135

| methods   |   adpe |   adpf |   avge |   avgf |   mae |   maxe |   maxf |    sm |   wfm |
|-----------|--------|--------|--------|--------|-------|--------|--------|-------|-------|
| OursDUT   |   0.95 |  0.886 |  0.946 |  0.885 | 0.027 |  0.949 |  0.894 | 0.907 |  0.87 |

Dataset: SIP

| methods   |   adpe |   adpf |   avge |   avgf |   mae |   maxe |   maxf |    sm |   wfm |
|-----------|--------|--------|--------|--------|-------|--------|--------|-------|-------|
| OursDUT   |  0.889 |  0.821 |  0.885 |  0.821 | 0.075 |  0.888 |  0.835 | 0.831 | 0.781 |

Dataset: SSD

| methods   |   adpe |   adpf |   avge |   avgf |   mae |   maxe |   maxf |    sm |   wfm |
|-----------|--------|--------|--------|--------|-------|--------|--------|-------|-------|
| OursDUT   |  0.884 |  0.795 |  0.882 |  0.795 |  0.07 |  0.889 |  0.812 | 0.832 | 0.767 |

Dataset: STEREO1000

| methods   |   adpe |   adpf |   avge |   avgf |   mae |   maxe |   maxf |    sm |   wfm |
|-----------|--------|--------|--------|--------|-------|--------|--------|-------|-------|
| OursDUT   |  0.935 |  0.869 |  0.933 |  0.868 | 0.043 |   0.94 |   0.89 | 0.887 | 0.853 |

——

这是我的环境：

```
# Automatically generated by https://github.com/damnever/pigar.

Pillow == 8.4.0
ml_collections == 0.1.1
numpy == 1.20.3
opencv_python_headless == 4.5.4.60
pysodmetrics == 1.3.0
scipy == 1.7.3
torch == 1.10.1
torchvision == 0.11.2
```

**Comment by liuzywen** [comment]
您好，感谢您的关注。我们分析了原因，可能是因为测试集中的深度图不同造成的。我们的深度图是离得近的是白色、离得远的的是黑色。还有一种可能是评测指标不同。所以我们上传了我们的测试集和评测指标。如果还有疑问，可以联系我liuzywen@ahu.edu.cn.

**Comment by lartpang** [comment]
@liuzywen 感谢回复，经过重新测试后确实是我的数据不一致。
